# Generated by Django 5.0.14 on 2026-01-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Beast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("attack_power", models.PositiveIntegerField(default=1)),
                ("attack_speed", models.PositiveIntegerField(default=1)),
                ("defense", models.PositiveIntegerField(default=1)),
                (
                    "found",
                    models.CharField(
                        choices=[
                            ("Nebula Forest", "Nebula Forest"),
                            ("Green Plains", "Green Plains"),
                            ("Red Desert", "Red Desert"),
                            ("Abyssal Ocean", "Abyssal Ocean"),
                            ("Unknown", "Unknown"),
                        ],
                        default="Unknown",
                        max_length=50,
                    ),
                ),
                (
                    "threat_level",
                    models.CharField(
                        choices=[
                            ("1_EASY", "Easy"),
                            ("2_MEDIUM", "Medium"),
                            ("3_HARD", "Hard"),
                            ("4_EXTRA_HARD", "Extra Hard"),
                            ("5_MEGA_HARD", "Mega Hard"),
                            ("6_DEATHLY_HARD", "Deathly Hard"),
                        ],
                        default="1_EASY",
                        max_length=50,
                    ),
                ),
                ("is_legendary", models.BooleanField(default=False)),
                ("notable_attack", models.TextField()),
                ("quirky_behavior", models.TextField()),
            ],
        ),
    ]
