# Generated by Django 5.0.14 on 2026-01-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Spell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spell_name", models.CharField(max_length=200)),
                ("spell_mana_cost", models.IntegerField()),
                (
                    "spell_element_type",
                    models.CharField(
                        choices=[
                            ("No Type", "None"),
                            ("Fire", "Fire"),
                            ("Water", "Water"),
                            ("Earth", "Earth"),
                            ("Air", "Air"),
                            ("Darkness", "Dark"),
                            ("Light", "Light"),
                        ],
                        default="No Type",
                        max_length=50,
                    ),
                ),
                ("spell_ingredients", models.TextField(blank=True, null=True)),
                ("spell_directions", models.TextField(blank=True, null=True)),
                ("spell_is_forbidden", models.BooleanField(default=False)),
            ],
        ),
    ]
