# Generated by Django 5.0.14 on 2026-01-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APP_spellbook", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="spell",
            name="spell_tags",
            field=models.ManyToManyField(to="APP_spellbook.tag", verbose_name="tags"),
        ),
    ]
