# Generated by Django 5.0.14 on 2026-03-05 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Claim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                ("task_information", models.TextField(verbose_name="")),
                (
                    "task_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Bounty", "Bounty"),
                            ("Delivery", "Delivery"),
                            ("Scouting Run", "Scouting Run"),
                            ("None", "None"),
                        ],
                        default="None",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Posted", "Posted"),
                            ("Hidden", "Hidden"),
                            ("Public and Unclaimed", "Public and Unclaimed"),
                            ("Claimed", "Claimed"),
                            ("Completed", "Completed"),
                        ],
                        default="Hidden",
                        max_length=150,
                    ),
                ),
                ("reward", models.PositiveIntegerField()),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, verbose_name=""),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "claimer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_created"],
            },
        ),
    ]
