# Generated by Django 5.0.14 on 2026-02-18 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Claim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Bounty", "Bnt"),
                            ("Delivery", "Del"),
                            ("Scouting Run", "Run"),
                            ("None", "None"),
                        ],
                        default="None",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Unclaimed", "Open"),
                            ("Claimed", "Claimed"),
                            ("Completed", "Completed"),
                        ],
                        default="Unclaimed",
                        max_length=150,
                    ),
                ),
                ("reward", models.PositiveIntegerField()),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, verbose_name=""),
                ),
                (
                    "claimer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_created"],
            },
        ),
    ]
