# Generated by Django 5.0.14 on 2026-02-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APP_board", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="task_information",
            field=models.TextField(default="", verbose_name=""),
            preserve_default=False,
        ),
    ]
