# Generated by Django 5.0.14 on 2026-03-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APP_board", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("Draft", "Draft"),
                    ("Posted", "Posted"),
                    ("Claimed", "Claimed"),
                    ("Completed", "Completed"),
                ],
                default="Draft",
                max_length=150,
            ),
        ),
    ]
