# Generated by Django 5.0.14 on 2026-02-04 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APP_encounter", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encounterentry",
            name="creature",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="APP_encounter.creature",
            ),
        ),
        migrations.AlterField(
            model_name="encounterentry",
            name="encounter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="APP_encounter.encounter",
            ),
        ),
        migrations.AlterField(
            model_name="encounterentry",
            name="quantity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
