# Generated by Django 5.0.14 on 2026-02-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APP_inventory", "0002_alter_item_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="first_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="character",
            name="last_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="character",
            name="player_character_name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="item",
            name="item_description",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="item",
            name="item_name",
            field=models.CharField(max_length=200),
        ),
    ]
