# Generated by Django 5.0.14 on 2026-02-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "APP_inventory",
            "0003_alter_character_first_name_alter_character_last_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="transferlog",
            name="transfer_created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
