# Generated by Django 5.0.14 on 2026-02-06 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APP_inventory", "0004_transferlog_transfer_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transferlog",
            name="transfer_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transfers",
                to="APP_inventory.character",
            ),
        ),
        migrations.AlterField(
            model_name="transferlog",
            name="transfer_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="APP_inventory.character",
            ),
        ),
    ]
