# Generated by Django 5.0.14 on 2026-01-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("body", models.CharField(max_length=50)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[("EZ", "Easy"), ("MD", "Medium"), ("HD", "Hard")],
                        default="EZ",
                        max_length=20,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("reward", models.IntegerField()),
            ],
        ),
    ]
