# Generated by Django 5.0.14 on 2026-01-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APP_board", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quest",
            options={"ordering": ["-created_on"]},
        ),
        migrations.AddField(
            model_name="quest",
            name="open_or_closed",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="quest",
            name="body",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="quest",
            name="difficulty",
            field=models.CharField(
                choices=[("Easy", "EZ"), ("Medium", "MED"), ("Hard", "HD")],
                default="Easy",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="quest",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
