# Generated by Django 5.0.14 on 2026-02-11 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("information_text", models.TextField()),
                ("slug", models.SlugField(max_length=220)),
                ("is_public", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="field_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Confirmation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="confirmations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "field_note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="confirmations",
                        to="APP_notes.fieldnote",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="fieldnote",
            constraint=models.UniqueConstraint(
                fields=("author", "slug"), name="unique_slug_per_author"
            ),
        ),
        migrations.AddConstraint(
            model_name="confirmation",
            constraint=models.UniqueConstraint(
                fields=("scout", "field_note"),
                name="unique_confimration_per_scount_per_note",
            ),
        ),
    ]
